#ifndef BABYLON_PROCEDURAL_TEXTURES_LIBRARY_BRICK_BRICK_PROCEDURAL_TEXTURE_FRAGMENT_FX_H
#define BABYLON_PROCEDURAL_TEXTURES_LIBRARY_BRICK_BRICK_PROCEDURAL_TEXTURE_FRAGMENT_FX_H

namespace BABYLON {

extern const char* brickProceduralTexturePixelShader;

const char* brickProceduralTexturePixelShader
  = "#ifdef GL_ES\n"
    "precision highp float;\n"
    "#endif\n"
    "\n"
    "varying vec2 vPosition;\n"
    "varying vec2 vUV;\n"
    "\n"
    "uniform float numberOfBricksHeight;\n"
    "uniform float numberOfBricksWidth;\n"
    "uniform vec3 brickColor;\n"
    "uniform vec3 jointColor;\n"
    "\n"
    "float rand(vec2 n) {\n"
    "  return fract(cos(dot(n, vec2(12.9898, 4.1414))) * 43758.5453);\n"
    "}\n"
    "\n"
    "float noise(vec2 n) {\n"
    "  const vec2 d = vec2(0.0, 1.0);\n"
    "  vec2 b = floor(n), f = smoothstep(vec2(0.0), vec2(1.0), fract(n));\n"
    "  return mix(mix(rand(b), rand(b + d.yx), f.x), mix(rand(b + d.xy), rand(b + d.yy), f.x), f.y);\n"
    "}\n"
    "\n"
    "float fbm(vec2 n) {\n"
    "  float total = 0.0, amplitude = 1.0;\n"
    "  for (int i = 0; i < 4; i++) {\n"
    "  total += noise(n) * amplitude;\n"
    "  n += n;\n"
    "  amplitude *= 0.5;\n"
    "  }\n"
    "  return total;\n"
    "}\n"
    "\n"
    "float round(float number){\n"
    "  return sign(number)*floor(abs(number) + 0.5);\n"
    "}\n"
    "\n"
    "void main(void)\n"
    "{\n"
    "  float brickW = 1.0 / numberOfBricksWidth;\n"
    "  float brickH = 1.0 / numberOfBricksHeight;\n"
    "  float jointWPercentage = 0.01;\n"
    "  float jointHPercentage = 0.05;\n"
    "  vec3 color = brickColor;\n"
    "  float yi = vUV.y / brickH;\n"
    "  float nyi = round(yi);\n"
    "  float xi = vUV.x / brickW;\n"
    "\n"
    "  if (mod(floor(yi), 2.0) == 0.0){\n"
    "  xi = xi - 0.5;\n"
    "  }\n"
    "\n"
    "  float nxi = round(xi);\n"
    "  vec2 brickvUV = vec2((xi - floor(xi)) / brickH, (yi - floor(yi)) /  brickW);\n"
    "\n"
    "  if (yi < nyi + jointHPercentage && yi > nyi - jointHPercentage){\n"
    "  color = mix(jointColor, vec3(0.37, 0.25, 0.25), (yi - nyi) / jointHPercentage + 0.2);\n"
    "  }\n"
    "  else if (xi < nxi + jointWPercentage && xi > nxi - jointWPercentage){\n"
    "  color = mix(jointColor, vec3(0.44, 0.44, 0.44), (xi - nxi) / jointWPercentage + 0.2);\n"
    "  }\n"
    "  else {\n"
    "  float brickColorSwitch = mod(floor(yi) + floor(xi), 3.0);\n"
    "\n"
    "  if (brickColorSwitch == 0.0)\n"
    "  color = mix(color, vec3(0.33, 0.33, 0.33), 0.3);\n"
    "  else if (brickColorSwitch == 2.0)\n"
    "  color = mix(color, vec3(0.11, 0.11, 0.11), 0.3);\n"
    "  }\n"
    "\n"
    "  gl_FragColor = vec4(color, 1.0);\n"
    "}\n";

} // end of namespace BABYLON

#endif // end of BABYLON_PROCEDURAL_TEXTURES_LIBRARY_BRICK_BRICK_PROCEDURAL_TEXTURE_FRAGMENT_FX_H
