#include <babylon/materials/pbr_material_defines.h>

namespace BABYLON {

PBRMaterialDefines::PBRMaterialDefines() : MaterialDefines{}
{
  _keys = {"ALBEDO",
           "AMBIENT",
           "AMBIENTINGRAYSCALE",
           "OPACITY",
           "OPACITYRGB",
           "REFLECTION",
           "EMISSIVE",
           "REFLECTIVITY",
           "BUMP",
           "PARALLAX",
           "PARALLAXOCCLUSION",
           "SPECULAROVERALPHA",
           "CLIPPLANE",
           "ALPHATEST",
           "ALPHAFROMALBEDO",
           "POINTSIZE",
           "FOG",
           "SPECULARTERM",
           "OPACITYFRESNEL",
           "EMISSIVEFRESNEL",
           "FRESNEL",
           "NORMAL",
           "TANGENT",
           "UV1",
           "UV2",
           "VERTEXCOLOR",
           "VERTEXALPHA",
           "INSTANCES",
           "MICROSURFACEFROMREFLECTIVITYMAP",
           "MICROSURFACEAUTOMATIC",
           "EMISSIVEASILLUMINATION",
           "LINKEMISSIVEWITHALBEDO",
           "LIGHTMAP",
           "USELIGHTMAPASSHADOWMAP",
           "REFLECTIONMAP_3D",
           "REFLECTIONMAP_SPHERICAL",
           "REFLECTIONMAP_PLANAR",
           "REFLECTIONMAP_CUBIC",
           "REFLECTIONMAP_PROJECTION",
           "REFLECTIONMAP_SKYBOX",
           "REFLECTIONMAP_EXPLICIT",
           "REFLECTIONMAP_EQUIRECTANGULAR",
           "REFLECTIONMAP_EQUIRECTANGULAR_FIXED",
           "REFLECTIONMAP_MIRROREDEQUIRECTANGULAR_FIXED",
           "INVERTCUBICMAP",
           "LOGARITHMICDEPTH",
           "CAMERATONEMAP",
           "CAMERACONTRAST",
           "CAMERACOLORGRADING",
           "CAMERACOLORCURVES",
           "OVERLOADEDVALUES",
           "OVERLOADEDSHADOWVALUES",
           "USESPHERICALFROMREFLECTIONMAP",
           "REFRACTION",
           "REFRACTIONMAP_3D",
           "LINKREFRACTIONTOTRANSPARENCY",
           "REFRACTIONMAPINLINEARSPACE",
           "LODBASEDMICROSFURACE",
           "USEPHYSICALLIGHTFALLOFF",
           "RADIANCEOVERALPHA",
           "USEPMREMREFLECTION",
           "USEPMREMREFRACTION",
           "INVERTNORMALMAPX",
           "INVERTNORMALMAPY",
           "TWOSIDEDLIGHTING",
           "SHADOWFULLFLOAT",
           "METALLICWORKFLOW",
           "METALLICMAP",
           "ROUGHNESSSTOREINMETALMAPALPHA",
           "ROUGHNESSSTOREINMETALMAPGREEN",
           "METALLNESSSTOREINMETALMAPBLUE",
           "AOSTOREINMETALMAPRED",
           "MICROSURFACEMAP",
           "MORPHTARGETS",
           "MORPHTARGETS_NORMAL"};
  rebuild();
}

PBRMaterialDefines::~PBRMaterialDefines()
{
}

} // end of namespace BABYLON
