#ifndef BABYLON_SHADERS_SHADERS_INCLUDE_DEFAULT_FRAGMENT_DECLARATION_FX_H
#define BABYLON_SHADERS_SHADERS_INCLUDE_DEFAULT_FRAGMENT_DECLARATION_FX_H

namespace BABYLON {

extern const char* defaultFragmentDeclaration;

const char* defaultFragmentDeclaration
  = "uniform vec4 vDiffuseColor;\n"
    "#ifdef SPECULARTERM\n"
    "uniform vec4 vSpecularColor;\n"
    "#endif\n"
    "uniform vec3 vEmissiveColor;\n"
    "\n"
    "uniform float visibility;\n"
    "\n"
    "// Samplers\n"
    "#ifdef DIFFUSE\n"
    "uniform vec2 vDiffuseInfos;\n"
    "#endif\n"
    "\n"
    "#ifdef AMBIENT\n"
    "uniform vec2 vAmbientInfos;\n"
    "#endif\n"
    "\n"
    "#ifdef OPACITY  \n"
    "uniform vec2 vOpacityInfos;\n"
    "#endif\n"
    "\n"
    "#ifdef EMISSIVE\n"
    "uniform vec2 vEmissiveInfos;\n"
    "#endif\n"
    "\n"
    "#ifdef LIGHTMAP\n"
    "uniform vec2 vLightmapInfos;\n"
    "#endif\n"
    "\n"
    "#ifdef BUMP\n"
    "uniform vec3 vBumpInfos;\n"
    "uniform vec2 vTangentSpaceParams;\n"
    "#endif\n"
    "\n"
    "#if defined(REFLECTIONMAP_SPHERICAL) || defined(REFLECTIONMAP_PROJECTION) || defined(REFRACTION)\n"
    "uniform mat4 view;\n"
    "#endif\n"
    "\n"
    "#ifdef REFRACTION\n"
    "uniform vec4 vRefractionInfos;\n"
    "\n"
    "#ifndef REFRACTIONMAP_3D\n"
    "uniform mat4 refractionMatrix;\n"
    "#endif\n"
    "\n"
    "#ifdef REFRACTIONFRESNEL\n"
    "uniform vec4 refractionLeftColor;\n"
    "uniform vec4 refractionRightColor;\n"
    "#endif\n"
    "#endif\n"
    "\n"
    "#if defined(SPECULAR) && defined(SPECULARTERM)\n"
    "uniform vec2 vSpecularInfos;\n"
    "#endif\n"
    "\n"
    "#ifdef DIFFUSEFRESNEL\n"
    "uniform vec4 diffuseLeftColor;\n"
    "uniform vec4 diffuseRightColor;\n"
    "#endif\n"
    "\n"
    "#ifdef OPACITYFRESNEL\n"
    "uniform vec4 opacityParts;\n"
    "#endif\n"
    "\n"
    "#ifdef EMISSIVEFRESNEL\n"
    "uniform vec4 emissiveLeftColor;\n"
    "uniform vec4 emissiveRightColor;\n"
    "#endif\n"
    "\n"
    "// Reflection\n"
    "#ifdef REFLECTION\n"
    "uniform vec2 vReflectionInfos;\n"
    "\n"
    "  #if defined(REFLECTIONMAP_PLANAR) || defined(REFLECTIONMAP_CUBIC) || defined(REFLECTIONMAP_PROJECTION) || defined(REFLECTIONMAP_EQUIRECTANGULAR) || defined(REFLECTIONMAP_SPHERICAL) || defined(REFLECTIONMAP_SKYBOX)\n"
    "  uniform mat4 reflectionMatrix;\n"
    "  #endif\n"
    "\n"
    "  #ifndef REFLECTIONMAP_SKYBOX\n"
    "  #if defined(USE_LOCAL_REFLECTIONMAP_CUBIC) && defined(REFLECTIONMAP_CUBIC)\n"
    "  uniform vec3 vReflectionPosition;\n"
    "  uniform vec3 vReflectionSize; \n"
    "  #endif\n"
    "  #endif\n"
    "\n"
    "  #ifdef REFLECTIONFRESNEL\n"
    "  uniform vec4 reflectionLeftColor;\n"
    "  uniform vec4 reflectionRightColor;\n"
    "  #endif\n"
    "\n"
    "#endif\n";

} // end of namespace BABYLON

#endif // end of BABYLON_SHADERS_SHADERS_INCLUDE_DEFAULT_FRAGMENT_DECLARATION_FX_H
