#ifndef BABYLON_SHADERS_SHADERS_INCLUDE_LIGHT_FRAGMENT_FX_H
#define BABYLON_SHADERS_SHADERS_INCLUDE_LIGHT_FRAGMENT_FX_H

namespace BABYLON {

extern const char* lightFragment;

const char* lightFragment
  = "#ifdef LIGHT{X}\n"
    "  #if defined(SHADOWONLY) || (defined(LIGHTMAP) && defined(LIGHTMAPEXCLUDED{X}) && defined(LIGHTMAPNOSPECULAR{X}))\n"
    "  //No light calculation\n"
    "  #else\n"
    "  #ifdef PBR\n"
    "  #ifdef SPOTLIGHT{X}\n"
    "  info = computeSpotLighting(viewDirectionW, normalW, light{X}.vLightData, light{X}.vLightDirection, light{X}.vLightDiffuse.rgb, light{X}.vLightSpecular, light{X}.vLightDiffuse.a, roughness, NdotV, specularEnvironmentR0, specularEnvironmentR90, geometricRoughnessFactor, NdotL);\n"
    "  #endif\n"
    "  #ifdef HEMILIGHT{X}\n"
    "  info = computeHemisphericLighting(viewDirectionW, normalW, light{X}.vLightData, light{X}.vLightDiffuse.rgb, light{X}.vLightSpecular, light{X}.vLightGround, roughness, NdotV, specularEnvironmentR0, specularEnvironmentR90, geometricRoughnessFactor, NdotL);\n"
    "  #endif\n"
    "  #if defined(POINTLIGHT{X}) || defined(DIRLIGHT{X})\n"
    "  info = computeLighting(viewDirectionW, normalW, light{X}.vLightData, light{X}.vLightDiffuse.rgb, light{X}.vLightSpecular, light{X}.vLightDiffuse.a, roughness, NdotV, specularEnvironmentR0, specularEnvironmentR90, geometricRoughnessFactor, NdotL);\n"
    "  #endif\n"
    "  #else\n"
    "  #ifdef SPOTLIGHT{X}\n"
    "  info = computeSpotLighting(viewDirectionW, normalW, light{X}.vLightData, light{X}.vLightDirection, light{X}.vLightDiffuse.rgb, light{X}.vLightSpecular, light{X}.vLightDiffuse.a, glossiness);\n"
    "  #endif\n"
    "  #ifdef HEMILIGHT{X}\n"
    "  info = computeHemisphericLighting(viewDirectionW, normalW, light{X}.vLightData, light{X}.vLightDiffuse.rgb, light{X}.vLightSpecular, light{X}.vLightGround, glossiness);\n"
    "  #endif\n"
    "  #if defined(POINTLIGHT{X}) || defined(DIRLIGHT{X})\n"
    "  info = computeLighting(viewDirectionW, normalW, light{X}.vLightData, light{X}.vLightDiffuse.rgb, light{X}.vLightSpecular, light{X}.vLightDiffuse.a, glossiness);\n"
    "  #endif\n"
    "  #endif\n"
    "  #ifdef PROJECTEDLIGHTTEXTURE{X}\n"
    "  info.diffuse *= computeProjectionTextureDiffuseLighting(projectionLightSampler{X}, textureProjectionMatrix{X});\n"
    "  #endif\n"
    "  #endif\n"
    "  #ifdef SHADOW{X}\n"
    "  #ifdef SHADOWCLOSEESM{X}\n"
    "  #if defined(SHADOWCUBE{X})\n"
    "  shadow = computeShadowWithCloseESMCube(light{X}.vLightData.xyz, shadowSampler{X}, light{X}.shadowsInfo.x, light{X}.shadowsInfo.z, light{X}.depthValues);\n"
    "  #else\n"
    "  shadow = computeShadowWithCloseESM(vPositionFromLight{X}, vDepthMetric{X}, shadowSampler{X}, light{X}.shadowsInfo.x, light{X}.shadowsInfo.z, light{X}.shadowsInfo.w);\n"
    "  #endif\n"
    "  #elif defined(SHADOWESM{X})\n"
    "  #if defined(SHADOWCUBE{X})\n"
    "  shadow = computeShadowWithESMCube(light{X}.vLightData.xyz, shadowSampler{X}, light{X}.shadowsInfo.x, light{X}.shadowsInfo.z, light{X}.depthValues);\n"
    "  #else\n"
    "  shadow = computeShadowWithESM(vPositionFromLight{X}, vDepthMetric{X}, shadowSampler{X}, light{X}.shadowsInfo.x, light{X}.shadowsInfo.z, light{X}.shadowsInfo.w);\n"
    "  #endif\n"
    "  #elif defined(SHADOWPOISSON{X})\n"
    "  #if defined(SHADOWCUBE{X})\n"
    "  shadow = computeShadowWithPoissonSamplingCube(light{X}.vLightData.xyz, shadowSampler{X}, light{X}.shadowsInfo.y, light{X}.shadowsInfo.x, light{X}.depthValues);\n"
    "  #else\n"
    "  shadow = computeShadowWithPoissonSampling(vPositionFromLight{X}, vDepthMetric{X}, shadowSampler{X}, light{X}.shadowsInfo.y, light{X}.shadowsInfo.x, light{X}.shadowsInfo.w);\n"
    "  #endif\n"
    "  #elif defined(SHADOWPCF{X})\n"
    "  #if defined(SHADOWLOWQUALITY{X})\n"
    "  shadow = computeShadowWithPCF1(vPositionFromLight{X}, vDepthMetric{X}, shadowSampler{X}, light{X}.shadowsInfo.x, light{X}.shadowsInfo.w);\n"
    "  #elif defined(SHADOWMEDIUMQUALITY{X})\n"
    "  shadow = computeShadowWithPCF3(vPositionFromLight{X}, vDepthMetric{X}, shadowSampler{X}, light{X}.shadowsInfo.yz, light{X}.shadowsInfo.x, light{X}.shadowsInfo.w);\n"
    "  #else\n"
    "  shadow = computeShadowWithPCF5(vPositionFromLight{X}, vDepthMetric{X}, shadowSampler{X}, light{X}.shadowsInfo.yz, light{X}.shadowsInfo.x, light{X}.shadowsInfo.w);\n"
    "  #endif\n"
    "  #elif defined(SHADOWPCSS{X})\n"
    "  #if defined(SHADOWLOWQUALITY{X})\n"
    "  shadow = computeShadowWithPCSS16(vPositionFromLight{X}, vDepthMetric{X}, depthSampler{X}, shadowSampler{X}, light{X}.shadowsInfo.y, light{X}.shadowsInfo.z, light{X}.shadowsInfo.x, light{X}.shadowsInfo.w);\n"
    "  #elif defined(SHADOWMEDIUMQUALITY{X})\n"
    "  shadow = computeShadowWithPCSS32(vPositionFromLight{X}, vDepthMetric{X}, depthSampler{X}, shadowSampler{X}, light{X}.shadowsInfo.y, light{X}.shadowsInfo.z, light{X}.shadowsInfo.x, light{X}.shadowsInfo.w);\n"
    "  #else\n"
    "  shadow = computeShadowWithPCSS64(vPositionFromLight{X}, vDepthMetric{X}, depthSampler{X}, shadowSampler{X}, light{X}.shadowsInfo.y, light{X}.shadowsInfo.z, light{X}.shadowsInfo.x, light{X}.shadowsInfo.w);\n"
    "  #endif\n"
    "  #else\n"
    "  #if defined(SHADOWCUBE{X})\n"
    "  shadow = computeShadowCube(light{X}.vLightData.xyz, shadowSampler{X}, light{X}.shadowsInfo.x, light{X}.depthValues);\n"
    "  #else\n"
    "  shadow = computeShadow(vPositionFromLight{X}, vDepthMetric{X}, shadowSampler{X}, light{X}.shadowsInfo.x, light{X}.shadowsInfo.w);\n"
    "  #endif\n"
    "  #endif\n"
    "\n"
    "  #ifdef SHADOWONLY\n"
    "  #ifndef SHADOWINUSE\n"
    "  #define SHADOWINUSE\n"
    "  #endif\n"
    "  globalShadow += shadow;\n"
    "  shadowLightCount += 1.0;\n"
    "  #endif\n"
    "  #else\n"
    "  shadow = 1.;\n"
    "  #endif\n"
    "\n"
    "  #ifndef SHADOWONLY\n"
    "  #ifdef CUSTOMUSERLIGHTING\n"
    "  diffuseBase += computeCustomDiffuseLighting(info, diffuseBase, shadow);\n"
    "  #ifdef SPECULARTERM\n"
    "  specularBase += computeCustomSpecularLighting(info, specularBase, shadow);\n"
    "  #endif\n"
    "  #elif defined(LIGHTMAP) && defined(LIGHTMAPEXCLUDED{X})\n"
    "  diffuseBase += lightmapColor * shadow;\n"
    "  #ifdef SPECULARTERM\n"
    "  #ifndef LIGHTMAPNOSPECULAR{X}\n"
    "  specularBase += info.specular * shadow * lightmapColor;\n"
    "  #endif\n"
    "  #endif\n"
    "  #else\n"
    "  diffuseBase += info.diffuse * shadow;\n"
    "  #ifdef SPECULARTERM\n"
    "  specularBase += info.specular * shadow;\n"
    "  #endif\n"
    "  #endif\n"
    "  #endif\n"
    "#endif\n";

} // end of namespace BABYLON

#endif // end of BABYLON_SHADERS_SHADERS_INCLUDE_LIGHT_FRAGMENT_FX_H
