#ifndef BABYLON_SHADERS_SHADERS_INCLUDE_PBR_FRAGMENT_DECLARATION_FX_H
#define BABYLON_SHADERS_SHADERS_INCLUDE_PBR_FRAGMENT_DECLARATION_FX_H

namespace BABYLON {

extern const char* pbrFragmentDeclaration;

const char* pbrFragmentDeclaration
  = "uniform vec3 vReflectionColor;\n"
    "uniform vec4 vAlbedoColor;\n"
    "\n"
    "// CUSTOM CONTROLS\n"
    "uniform vec4 vLightingIntensity;\n"
    "\n"
    "uniform vec4 vReflectivityColor;\n"
    "uniform vec3 vEmissiveColor;\n"
    "\n"
    "uniform float visibility;\n"
    "\n"
    "// Samplers\n"
    "#ifdef ALBEDO\n"
    "uniform vec2 vAlbedoInfos;\n"
    "#endif\n"
    "\n"
    "#ifdef AMBIENT\n"
    "uniform vec4 vAmbientInfos;\n"
    "#endif\n"
    "\n"
    "#ifdef BUMP\n"
    "uniform vec3 vBumpInfos;\n"
    "uniform vec2 vTangentSpaceParams;\n"
    "#endif\n"
    "\n"
    "#ifdef OPACITY\n"
    "uniform vec2 vOpacityInfos;\n"
    "#endif\n"
    "\n"
    "#ifdef EMISSIVE\n"
    "uniform vec2 vEmissiveInfos;\n"
    "#endif\n"
    "\n"
    "#ifdef LIGHTMAP\n"
    "uniform vec2 vLightmapInfos;\n"
    "#endif\n"
    "\n"
    "#ifdef REFLECTIVITY\n"
    "uniform vec3 vReflectivityInfos;\n"
    "#endif\n"
    "\n"
    "#ifdef MICROSURFACEMAP\n"
    "uniform vec2 vMicroSurfaceSamplerInfos;\n"
    "#endif\n"
    "\n"
    "// Refraction Reflection\n"
    "#if defined(REFLECTIONMAP_SPHERICAL) || defined(REFLECTIONMAP_PROJECTION) || defined(SS_REFRACTION)\n"
    "uniform mat4 view;\n"
    "#endif\n"
    "\n"
    "// Reflection\n"
    "#ifdef REFLECTION\n"
    "  uniform vec2 vReflectionInfos;\n"
    "  uniform mat4 reflectionMatrix;\n"
    "  uniform vec3 vReflectionMicrosurfaceInfos;\n"
    "\n"
    "  #if defined(USE_LOCAL_REFLECTIONMAP_CUBIC) && defined(REFLECTIONMAP_CUBIC)\n"
    "  uniform vec3 vReflectionPosition;\n"
    "  uniform vec3 vReflectionSize; \n"
    "  #endif\n"
    "#endif\n"
    "\n"
    "// Clear Coat\n"
    "#ifdef CLEARCOAT\n"
    "  uniform vec2 vClearCoatParams;\n"
    "  uniform vec4 vClearCoatRefractionParams;\n"
    "\n"
    "  #ifdef CLEARCOAT_TEXTURE\n"
    "  uniform vec2 vClearCoatInfos;\n"
    "  uniform mat4 clearCoatMatrix;\n"
    "  #endif\n"
    "\n"
    "  #ifdef CLEARCOAT_BUMP\n"
    "  uniform vec2 vClearCoatBumpInfos;\n"
    "  uniform vec2 vClearCoatTangentSpaceParams;\n"
    "  uniform mat4 clearCoatBumpMatrix;\n"
    "  #endif\n"
    "\n"
    "  #ifdef CLEARCOAT_TINT\n"
    "  uniform vec4 vClearCoatTintParams;\n"
    "  uniform float clearCoatColorAtDistance;\n"
    "\n"
    "  #ifdef CLEARCOAT_TINT_TEXTURE\n"
    "  uniform vec2 vClearCoatTintInfos;\n"
    "  uniform mat4 clearCoatTintMatrix;\n"
    "  #endif\n"
    "  #endif\n"
    "#endif\n"
    "\n"
    "// Anisotropy\n"
    "#ifdef ANISOTROPIC\n"
    "  uniform vec3 vAnisotropy;\n"
    "\n"
    "  #ifdef ANISOTROPIC_TEXTURE\n"
    "  uniform vec2 vAnisotropyInfos;\n"
    "  uniform mat4 anisotropyMatrix;\n"
    "  #endif\n"
    "#endif\n"
    "\n"
    "// Sheen\n"
    "#ifdef SHEEN\n"
    "  uniform vec4 vSheenColor;\n"
    "\n"
    "  #ifdef SHEEN_TEXTURE\n"
    "  uniform vec2 vSheenInfos;\n"
    "  uniform mat4 sheenMatrix;\n"
    "  #endif\n"
    "#endif\n"
    "\n"
    "// SubSurface\n"
    "#ifdef SUBSURFACE\n"
    "  #ifdef SS_REFRACTION\n"
    "  uniform vec3 vRefractionMicrosurfaceInfos;\n"
    "  uniform vec4 vRefractionInfos;\n"
    "  uniform mat4 refractionMatrix;\n"
    "  #endif\n"
    "\n"
    "  #ifdef SS_THICKNESSANDMASK_TEXTURE\n"
    "  uniform vec2 vThicknessInfos;\n"
    "  uniform mat4 thicknessMatrix;;\n"
    "  #endif\n"
    "\n"
    "  uniform vec2 vThicknessParam;\n"
    "  uniform vec3 vDiffusionDistance;\n"
    "  uniform vec4 vTintColor;\n"
    "  uniform vec3 vSubSurfaceIntensity;\n"
    "#endif\n";

} // end of namespace BABYLON

#endif // end of BABYLON_SHADERS_SHADERS_INCLUDE_PBR_FRAGMENT_DECLARATION_FX_H
